### ISSUE TITLE
Out-of-dated documentation

### ISSUE THREAD

**Issue by tttturtle-russ** [SVF-tools/Software-Security-Analysis#29]
Hi, thanks for your brilliant work and courses.
I've been taking this course lately and have found some problems in Wiki. The CPP API reference seems to have some incorrectness, i.e [ICFGEdge](https://github.com/SVF-tools/Software-Security-Analysis/wiki/SVF-CPP-API#icfgedge), in practice the class CallCFGEdge does not have `getCallSite` method, I have to do this to get call site.
```
auto node = dyn_cast<CallICFGNode>(edge->getSrcNode());
node.getCallSite();
```
This confused me for a while. Maybe I've done something wrong?
Waiting for your reply and answers :) Thanks a lot.

**Comment by yuleisui** [comment]
Thanks for pointing it out. This is due to a recent SVF refactoring.

The method is now back in the SVF's upstream:
https://github.com/SVF-tools/SVF/commit/0059690aad6c239cc9518bb86b5288e7c17cf13e

**Comment by tttturtle-russ** [comment]
Thanks for your reply. But according to the doc description, `getCallsite` supposes to return a llvm instruction rather than a node.

**Comment by yuleisui** [comment]
Updated.

**Comment by tttturtle-russ** [comment]
Thank you！
